# Generated by Django 4.2.13 on 2024-05-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=20)),
                ('value', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
