# Generated by Django 4.2.13 on 2024-05-29 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('order', 'Order'), ('booking', 'Booking')], default='info', max_length=10)),
            ],
        ),
    ]
