# Generated by Django 4.2.13 on 2024-05-16 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('item', models.ManyToManyField(to='restaurant.item')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('is_meal', models.BooleanField(default=False)),
                ('spiciness_level', models.SmallIntegerField(blank=True, choices=[(0, 'Mild'), (0, 'Hot'), (2, 'Spicy')], null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='restaurant.category')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant.item')),
                ('optional_items', models.ManyToManyField(blank=True, null=True, to='restaurant.item')),
                ('required_items', models.ManyToManyField(blank=True, null=True, to='restaurant.requireditem')),
            ],
        ),
    ]
