# Generated by Django 4.2.13 on 2024-05-17 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.SmallIntegerField(choices=[(0, 'Pick-Up'), (1, 'Delivery')], default=1)),
                ('order_status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'In progress'), (2, 'Out for delivery'), (3, 'Delivered')], default=0)),
                ('address', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=111)),
                ('state', models.CharField(blank=True, max_length=111, null=True)),
                ('phone', models.CharField(default='', max_length=111)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allow_serving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegitarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='show_salad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='show_sauce',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='restaurant.item'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='optional_items',
            field=models.ManyToManyField(blank=True, to='restaurant.item'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='required_items',
            field=models.ManyToManyField(blank=True, to='restaurant.requireditem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='spiciness_level',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Mild'), (1, 'Hot'), (2, 'Spicy')], null=True),
        ),
        migrations.CreateModel(
            name='OrderMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.JSONField(blank=True, null=True)),
                ('serving', models.SmallIntegerField(blank=True, choices=[(0, 'Regular'), (1, 'Large')], null=True)),
                ('additional_items', models.ManyToManyField(blank=True, to='restaurant.item')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurant.order')),
            ],
        ),
    ]
