# Generated by Django 4.2.13 on 2024-05-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_order_menuitem_allow_serving_menuitem_is_vegitarian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeal',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
