# Generated by Django 4.2.13 on 2024-05-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_order_order_status_alter_ordermeal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermeal',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
