# Generated by Django 4.2.13 on 2024-05-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_ordermeal_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_code',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'Pick-Up'), (1, 'Delivery')], default=0),
        ),
    ]
