# Generated by Django 4.2.13 on 2024-05-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_order_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'Cash on Delivery'), (1, 'Online payment')], default=0),
        ),
        migrations.AlterField(
            model_name='ordermeal',
            name='serving',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Regular'), (2, 'Large')], null=True),
        ),
    ]
