# Generated by Django 4.2.13 on 2024-06-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_order_payment_method_alter_ordermeal_serving'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ordermeal',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem'),
        ),
        migrations.CreateModel(
            name='OrderReimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_refund_requested', models.BooleanField(default=False)),
                ('is_reimbursed', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('reason_for_reimbursed', models.TextField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement', to='restaurant.order')),
            ],
        ),
    ]
