# Generated by Django 4.2.13 on 2024-06-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_order_payment_intent_alter_ordermeal_menu_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'In progress'), (2, 'Out for delivery'), (3, 'Delivered'), (4, 'Paid'), (5, 'Reimbursed')], default=0),
        ),
    ]
