# Generated by Django 4.2.13 on 2024-05-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationConfig',
        ),
    ]
