# Generated by Django 4.2.13 on 2024-05-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_delete_reservationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationApproved',
            fields=[
            ],
            options={
                'verbose_name': 'Approved Reservation',
                'verbose_name_plural': 'Approved Reservations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reservation.reservation',),
        ),
        migrations.CreateModel(
            name='ReservationPending',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Reservation',
                'verbose_name_plural': 'Pending Reservations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reservation.reservation',),
        ),
    ]
