# Generated by Django 4.2.13 on 2024-05-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservationapproved_reservationpending'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='', max_length=111),
        ),
    ]
