# Generated by Django 4.2.13 on 2024-05-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationApproved',
        ),
        migrations.DeleteModel(
            name='ReservationPending',
        ),
    ]
